<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('AppBundle\\Controller\\ProgrammeController:showrrrrAction' => function () {
    return ${($_ = isset($this->services['service_locator.tm9qloa']) ? $this->services['service_locator.tm9qloa'] : $this->load('getServiceLocator_Tm9qloaService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\StatistiqueController:stateAction' => function () {
    return ${($_ = isset($this->services['service_locator.ymrdw7p']) ? $this->services['service_locator.ymrdw7p'] : $this->load('getServiceLocator_Ymrdw7pService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\ProgrammeController::showrrrrAction' => function () {
    return ${($_ = isset($this->services['service_locator.tm9qloa']) ? $this->services['service_locator.tm9qloa'] : $this->load('getServiceLocator_Tm9qloaService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\StatistiqueController::stateAction' => function () {
    return ${($_ = isset($this->services['service_locator.ymrdw7p']) ? $this->services['service_locator.ymrdw7p'] : $this->load('getServiceLocator_Ymrdw7pService.php')) && false ?: '_'};
})));
