<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'slot_mandrill.dispatcher' shared service.

return $this->services['slot_mandrill.dispatcher'] = new \Slot\MandrillBundle\Dispatcher(${($_ = isset($this->services['slot_mandrill.client']) ? $this->services['slot_mandrill.client'] : $this->services['slot_mandrill.client'] = new \Mandrill('pwpIkO8vhBQqZa8mV9tTrg')) && false ?: '_'}, 'clamm@bliwe.paris', 'bliwe', NULL, false, $this->parameters['slot_mandrill.proxy'], true);
