<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProduitWithSociete()
    {
        return $this->createQueryBuilder('p')
            ->leftJoin('p.id_societe', 'societe')
            ->addSelect('societe')
            ->leftJoin('p.nomenclature', 'nomenclature')
            ->addSelect('nomenclature')
            ->leftJoin('p.salon', 'salon')
            ->addSelect('salon')
            ->orderBy('societe.nom', 'ASC')
            ->getQuery()
            ->getResult()
            ;
    }

}
