<?php

namespace AppBundle\Repository;

/**
 * TcommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TcommentaireRepository extends \Doctrine\ORM\EntityRepository
{
}
