<?php

namespace AppBundle\Repository;

/**
 * TtokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TtokenRepository extends \Doctrine\ORM\EntityRepository
{
}
