<?php

namespace AppBundle\Repository;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getVoteWithProduit()
    {
        return $this->createQueryBuilder('v')
            ->leftJoin('v.societe', 'societe')
            ->addSelect('societe')
            ->leftJoin('v.produit', 'produit')
            ->addSelect('produit')
            ->getQuery()
            ->getResult()
            ;
    }
}
