<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'slot_mandrill.client' shared service.

return $this->services['slot_mandrill.client'] = new \Mandrill('pwpIkO8vhBQqZa8mV9tTrg');
